### ISSUE TITLE
Include the data file with the build

### ISSUE THREAD

**Issue by robmen** [2dave/github-testing#10]
To include data files, add the following to your .csproj.

    <ItemGroup>
      <Content Include="data\simple-3-list.txt" />
    </ItemGroup>

The `ItemGroup` can contain many elements (like `Content` which brings additional files along with the build) and the `Include` can use wildcards, even `**` which matches all directories recursively.

For example, to include **all* * text files in your project folder the following would work:

    <ItemGroup>
      <Content Include="**\*.txt" />
    </ItemGroup>

Try it so you don't have to hard code `C:\gittraining\github-testing\lister\`.

**Comment by 2dave** [comment]
I made the recommended changes above. It makes working with the .\data directory much easier and it looks cleaner.

**Comment by robmen** [comment]
Usually, you don't close issues until the code is committed to the "shipping" branch (in this case `master`).

**Comment by 2dave** [comment]
Learning the workflow. Reopening until the branch I was working on merges back with master.

**Comment by 2dave** [comment]
commit f9c84da04022eea1e418219d14750036b14d1c0d
Fixes #10.
However, since I already did the commit before I knew to put the fix number in the commit.

**Comment by robmen** [comment]
You can also put the issue number in the Pull Request comment (when you create the PR) for the cases where you forget to add the comment in a commit.
