### ISSUE TITLE
Comment style inconsistent

### ISSUE THREAD

**Issue by robmen** [2dave/github-testing#9]
Consider treating comments as sentences when standalone and finishing sentences when trailing code. For example:

    // This is a comment describing why we are doing what we are doing. Don't
    // explain what (unless the code is necessarily cryptic - aka: perf) but why.
    if (someComplexExpression)
    {
        ++i;
    }
    else // this happens when x, y, z are out of phase with the sun.
    {
        --i;
    }

Comments are designed to be read by humans, so following standards for humans (white space, grammar, periods, etc.) is generally a good idea.

**Comment by 2dave** [comment]
Will do. This kind of issue may be hard to fix in a single commit.
I'll put something in the next commit anyway to address it. Maybe a properly formatted comment in there :)

**Comment by robmen** [comment]
This is another case where putting the "Fixes #X" in the Pull Request comment may work out really well.
